import numpy as np
import torch

from functions.svd_operators import A_functions


class FourierGuidedOperator(A_functions):
    """
    Super-resolution operator with two Fourier anchors:

    - inter-slice anchor: very-low band from neighboring NAB-GS slice
    - intra-slice anchor: low-mid band from same-slice DDNM-first output
    - free band: remaining frequencies generated by diffusion
    """

    def __init__(self, base_operator, channels, img_dim, device, inter_radius, intra_radius, transition_width=8.0):
        super().__init__()
        self.base = base_operator
        self.channels = int(channels)
        self.img_dim = int(img_dim)
        self.device = torch.device(device)
        self.inter_radius = float(inter_radius)
        self.intra_radius = float(intra_radius)
        self.transition_width = float(max(transition_width, 1.0))

        inter_mask = self._build_low_mask(self.inter_radius)
        intra_full_mask = self._build_low_mask(self.intra_radius)
        intra_mask = torch.clamp(intra_full_mask - inter_mask, min=0.0, max=1.0)
        free_mask = torch.clamp(1.0 - intra_full_mask, min=0.0, max=1.0)

        self.inter_mask = inter_mask.unsqueeze(0).unsqueeze(0)
        self.intra_mask = intra_mask.unsqueeze(0).unsqueeze(0)
        self.free_mask = free_mask.unsqueeze(0).unsqueeze(0)

    def _build_low_mask(self, radius_limit):
        cy = self.img_dim // 2
        cx = self.img_dim // 2
        y, x = np.indices((self.img_dim, self.img_dim))
        radius = np.sqrt((x - cx) ** 2 + (y - cy) ** 2).astype(np.float32)
        start = radius_limit - self.transition_width * 0.5
        t = (radius - start) / self.transition_width
        t = np.clip(t, 0.0, 1.0)
        smooth = t * t * (3.0 - 2.0 * t)
        low = 1.0 - smooth
        return torch.from_numpy(low.astype(np.float32)).to(self.device)

    def _to_image(self, x):
        if x.dim() == 4:
            return x
        if x.dim() == 2:
            return x.view(x.shape[0], self.channels, self.img_dim, self.img_dim)
        raise ValueError(f"Unexpected tensor shape: {x.shape}")

    def _fft2(self, x):
        return torch.fft.fftshift(torch.fft.fft2(x, norm="ortho"), dim=(-2, -1))

    def _ifft2(self, X):
        return torch.fft.ifft2(torch.fft.ifftshift(X, dim=(-2, -1)), norm="ortho").real

    def _apply_mask(self, x, mask):
        x_img = self._to_image(x)
        mask = mask.to(x_img.device).to(x_img.dtype).repeat(1, self.channels, 1, 1)
        return self._ifft2(self._fft2(x_img) * mask)

    def V(self, vec):
        return self.base.V(vec)

    def Vt(self, vec):
        return self.base.Vt(vec)

    def U(self, vec):
        return self.base.U(vec)

    def Ut(self, vec):
        return self.base.Ut(vec)

    def singulars(self):
        return self.base.singulars()

    def add_zeros(self, vec):
        return self.base.add_zeros(vec)

    def A(self, x):
        return self.base.A(x)

    def A_pinv(self, y):
        return self.base.A_pinv(y)

    def At(self, y):
        return self.base.At(y)

    def Lambda(self, vec, a, sigma_y, sigma_t, eta):
        return self.base.Lambda(vec, a, sigma_y, sigma_t, eta)

    def Lambda_noise(self, vec, a, sigma_y, sigma_t, eta, epsilon):
        return self.base.Lambda_noise(vec, a, sigma_y, sigma_t, eta, epsilon)

    def compose_guidance(self, sr_x, inter_ref_x, intra_ref_x):
        sr_img = self._to_image(sr_x)
        inter_img = self._to_image(inter_ref_x)
        intra_img = self._to_image(intra_ref_x)
        inter_band = self._apply_mask(inter_img, self.inter_mask)
        intra_band = self._apply_mask(intra_img, self.intra_mask)
        free_band = self._apply_mask(sr_img, self.free_mask)
        return inter_band + intra_band + free_band

    def compose_final(self, refined_x, inter_ref_x, intra_ref_x):
        refined_img = self._to_image(refined_x)
        inter_img = self._to_image(inter_ref_x)
        intra_img = self._to_image(intra_ref_x)
        inter_band = self._apply_mask(inter_img, self.inter_mask)
        intra_band = self._apply_mask(intra_img, self.intra_mask)
        refined_band = self._apply_mask(refined_img, self.free_mask)
        return inter_band + intra_band + refined_band


class FourierSRBand(FourierGuidedOperator):
    pass


class GrayChannelOperator(A_functions):
    """
    Adapter for operators that only work on a single channel.
    Assumes input images are grayscale replicated across channels and maps them
    through a 1-channel base operator, then broadcasts outputs back to all channels.
    """

    def __init__(self, base_operator, channels, img_dim, device):
        super().__init__()
        self.base = base_operator
        self.channels = int(channels)
        self.img_dim = int(img_dim)
        self.device = torch.device(device)

    def _to_image(self, x):
        if x.dim() == 4:
            return x
        if x.dim() == 2:
            return x.view(x.shape[0], self.channels, self.img_dim, self.img_dim)
        raise ValueError(f"Unexpected tensor shape: {x.shape}")

    def _first_channel_flat(self, x):
        x_img = self._to_image(x)
        return x_img[:, 0:1].reshape(x_img.shape[0], -1)

    def prepare_measurement(self, y):
        if y.dim() == 4:
            return y[:, 0:1].reshape(y.shape[0], -1)
        if y.dim() == 2 and y.shape[1] == self.channels * self.img_dim * self.img_dim:
            return self._first_channel_flat(y)
        return y

    def _repeat_channels(self, flat):
        if flat.dim() == 4:
            img = flat
        else:
            img = flat.view(flat.shape[0], 1, self.img_dim, self.img_dim)
        return img.repeat(1, self.channels, 1, 1).reshape(img.shape[0], -1)

    def V(self, vec):
        out = self.base.V(self._first_channel_flat(vec))
        return self._repeat_channels(out)

    def Vt(self, vec):
        out = self.base.Vt(self._first_channel_flat(vec))
        return self._repeat_channels(out)

    def U(self, vec):
        out = self.base.U(vec)
        return self._repeat_channels(out)

    def Ut(self, vec):
        out = self.base.Ut(self._first_channel_flat(vec))
        return self._repeat_channels(out)

    def singulars(self):
        return self.base.singulars()

    def add_zeros(self, vec):
        return self.base.add_zeros(vec)

    def A(self, x):
        return self.base.A(self._first_channel_flat(x))

    def A_pinv(self, y):
        out = self.base.A_pinv(self.prepare_measurement(y))
        return self._repeat_channels(out)

    def At(self, y):
        out = self.base.At(self.prepare_measurement(y))
        return self._repeat_channels(out)

    def Lambda(self, vec, a, sigma_y, sigma_t, eta):
        out = self.base.Lambda(vec, a, sigma_y, sigma_t, eta)
        return self._repeat_channels(out)

    def Lambda_noise(self, vec, a, sigma_y, sigma_t, eta, epsilon):
        out = self.base.Lambda_noise(vec, a, sigma_y, sigma_t, eta, epsilon)
        return self._repeat_channels(out)
